# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6, 3.7, 3.8]
    name: Python ${{ matrix.python-version }} example
    steps:
      - uses: actions/checkout@v3
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: which python
  # This workflow contains a single job called "build"
  # build:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version: ["3.10", "3.11", "3.12"]
  #       os: [ubuntu-latest, macos-latest]

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Setup conda
  #     uses: s-weigand/setup-conda@v1
  #     with:
  #       update-conda: true
  #       python-version: ${{ matrix.python-version }}
  #       conda-channels: anaconda, conda-forge
  #   - name: Install dependencies
  #     run: |
  #       conda create --yes -n test python=${{ matrix.python-version }}
  #       source activate test
  #       conda config --add channels conda-forge
  #       conda install --yes numpy scipy nose requests
  #       conda install --yes pdbfixer mdtraj openmm
  #       conda install --yes fortran-compiler cxx-compiler
  #       pip install mmtf-python scikit-learn
  #       cd prody/proteins/hpbmodule/
  #       gfortran -O3 -fPIC -c reg_tet.f
  #       variable=$(python -c 'from distutils.sysconfig import get_python_inc; print(get_python_inc())')
  #       c++ -O3 -g -fPIC -c hpbmodule.cpp -o hpbmodule.o -I/$variable
  #       c++ -shared -Wl,-soname,hpb.so -o hpb.so hpbmodule.o reg_tet.o -lgfortran
  #       cp hpb.so ../
  #       cd -
  #       pip install .
  #       python setup.py build_ext --inplace --force
  #   - name: Test with pytest
  #     run: |
  #       source activate test
  #       conda install --yes pytest
  #       pytest
